RefName: A
LastName: B
FirstName: C
County: D
Company: E
MainPhone: F
Code: G
Source: H
Plan: I
Type: J
CurrentInsurance: K
TypeOfCoverage: L
DateAdded: M
Status: N
Address1: O
Address2: P
City: Q
State: R
Zip: S
Email: T
DOB: U
SSN: V
Eff2Exp: W
Business: X
HireDate: Y
Effective: Z
PP: AA
CName1: AB
CDOB1: AC
CSSN1: AD
CPP1: AE
CName2: AF
CDOB2: AG
CSSN2: AH
CPP2: AI
Spouse: AJ
SpouseDOB: AK
SpouseSSN: AL
SpousePCP: AM
CName3: AN
CDOB3: AO
CSSN3: AP
CPCP3: AQ
CName4: AR
CDOB4: AS
CSSN4: AT
CPCP4: AU
Cur.Ins: AV
