Ref Name: A
Last: B
First: C
County: D
Company: E
Main: F
Code: G
Source: H
Plan: I
Type: J
Insurance: K
type of cvge: L
Date Added: M
Status: N
Address: O
Address2: P
City/St/Zip: Q
State: R
Zip: S
Email: T
DOB: U
SSN: V
eff.date/Exp: W
business: X
Hire Date: Y
Effective: Z
Primary Phy: AA
CName1: AB
CDOB1: AC
CSSN1: AD
CPCP1: AE
CName2: AF
CDOB2: AG
CSSN2: AH
CPCP2: AI
Spouse: AJ
SpouseDOB: AK
SpouseSSN: AL
SpousePCP: AM
CName3: AN
CDOB3: AO
CSSN3: AP
CPCP3: AQ
CName4: AR
CDOB4: AS
CSSN4: AT
CPCP4: AU
Cur.Ins/Brkr: AV
