LastName:		A
FirstName:		B
County:			C
Company:		D
MainPhone:		E
Code:			F
Source:			G
Plan:			H
Type:			I
CurrentInsurance:	J
TypeOfCoverage:		K
DateAdded:		M
Address1:		O
Address2:		P
City:			Q
State:			R
Zip:			S
County1:		T
Email:			U
DOB:			V
SSN:			W
Eff2Exp:		X
Y:			Y
Business:		Z
HireDate:		AA
Effective:		AB
PP:			AC
CName1:			AD
CDOB1:			AE
CSSN1:			AF
CPP1:			AG
CName2:			AH
CDOB2:			AI
CSSN2:			AJ
CPP2:			AK
Spouse:			AL
SpouseDOB:		AM
SpouseSSN:		AN
SpousePP:		AO
CName3:			AP
CDOB3:			AQ
CSSN3:			AR
CPP3:			AS
CName4:			AT
CDOB4:			AU
CSSN4:			AV
CPP4:			AW
